### PR TITLE
implement simple event emitter for FiltersEngine and sub-classes

### LINKED ISSUE #80: Implement event logger
To help debugging, it would be nice to implement an event logger for the adblocker. This would optionally keep track of requests blocked/redirected, exceptions as well as cosmetics injected into the page.

### LINKED ISSUE #247: adblock-electron: events on content blocking
Hi,

Would it be possible to emit some events in the case of a matched redirect/blocked url?

Having some events emitted will be useful to verify that the blocking works, otherwise there is no way to verify it.

Thanks.

### PR DESCRIPTION
**Pull request by remusao**
Following events are implemented:
* request-blocked
* request-redirected
* request-whitelisted
* csp-injected
* script-injected
* style-injected

Fixes #80 
Fixes #247

### CODE REVIEW

**Comment by char101** [comment]
Could there be a chance that these event names will conflict with the event names used in the user application or from another library?

**Comment by remusao** [comment]
> Could there be a chance that these event names will conflict with the event names used in the user application or from another library?

This should not happen as the events are "local" to the blocker instance. For example you can have two instances emitting the same events and register two different callbacks to each:

```js
const blocker1 = ElectronBlocker.parse('||domain1.com');
const blocker2 = ElectronBlocker.parse('||domain2.com');

blocker1.on('request-blocked', () => { console.log('blocker1!'); });
blocker2.on('request-blocked', () => { console.log('blocker2!'); });
```

Did I understand your question correctly?

**Comment by char101** [comment]
Sorry since I didn't see any example code I thought the events was implemented via electron's ipcMain/ipcRenderer (since I was using adblocker-electron). If the events is local to the adblocker then of course there should be no problem.

**Comment by remusao** [comment]
Indeed! I tried to implement this mechanism in such a way that all blockers can benefit from it: WebExtension, Electron, Puppeteer, etc. You can see a small example here: https://github.com/cliqz-oss/adblocker/blob/30d727d240ceca0e52f0c2089d8290bef8a1eff4/packages/adblocker-electron-example/index.ts#L70

**Comment by btzsoft** [comment]
@remusao when it's planned to be a new release for this? thx.

**Comment by remusao** [comment]
@btzsoft I was planning on releasing this with a few other changes that are in the pipeline but not related. But actually there is no strong reason to not release what is already on `master` (could be today), then release the rest in a few days when it's ready.

**Comment by btzsoft** [comment]
@remusao this would be great. Thank you!

**Comment by remusao** [comment]
@btzsoft done. Let me know if you encounter any issue.

**Comment by btzsoft** [comment]
@remusao I have an warning, is this ok?

```
WARNING in ./node_modules/@cliqz/adblocker/dist/es6/src/compression.js 25:34-41
[2] "export 'factory' was not found in 'tsmaz'
[2]  @ ./node_modules/@cliqz/adblocker/dist/es6/src/data-view.js
[2]  @ ./node_modules/@cliqz/adblocker/dist/es6/src/engine/engine.js
[2]  @ ./node_modules/@cliqz/adblocker/dist/es6/adblocker.js
[2]  @ ./app/modules/Browser/Adblock.js
....
```

**Comment by btzsoft** [comment]
the adblocker throws when try to parse

**Comment by remusao** [comment]
> the adblocker throws when try to parse

@btzsoft weird, this error should only happen if the installed version of `tsmaz` is `1.3.0` but the released version of the adblocker depends on `1.2.0`. Can you check in your `node_modules` which version of `tsmaz` is installed locally?

**Comment by btzsoft** [comment]
@remusao yes was `1.3.0`, changed to `1.2.0` and it's working now.

**Pull request merged**
