### PR TITLE
Adds support for using the puppeteer browser cache enabled when request interception is enabled

### LINKED ISSUE #1809: Can puppeteer browser caching be enabled by allowing request interception and caching at the same time?
I've been using this plugin with puppeteer via puppeteer-extra. I noticed that I haven't been able to get chrome's browser cache to work, and I think the reason is that [`page.setRequestInterception(true)`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagesetrequestinterceptionvalue-cachesafe), by default, disables caching. I noticed that there's an optional second argument called `cacheSafe` that sounds like it can be used to re-enable caching, e.g. `page.setRequestInterception(true, true)`.

I'm not familiar with why puppeteer disables caching by default when request interception is used, but it sounds like it's [because resources served from the cache aren't intercepted](https://github.com/puppeteer/puppeteer/issues/2905#issuecomment-406128495). That'd be fine for what I'm doing, since I've always used the adblocker plugin, so ads will never make it into the cache in the first place. It could be a problem for anyone who caches ad resources before they start using this plugin. They'd need to clear their cache.

I think making the change in this library would be as simple as adding the `cacheSafe` argument here:

https://github.com/cliqz-oss/adblocker/blob/e78aafb6ba3497bd1efa7fb66e8659f17d6765a7/packages/adblocker-puppeteer/adblocker.ts#L76

The option [was added very recently](https://github.com/puppeteer/puppeteer/pull/6996), so it might break compatibility. I don't think puppeteer-extra supports the latest puppeteer releases yet, for example.

### PR DESCRIPTION
**Pull request by Tyler-Murphy**
Closes #1809.

This works like puppeteer, in that you must opt in to using the cache when request interception is enabled. The default behavior of disabling the cache is preserved.

### CODE REVIEW

**Review by remusao — APPROVED** [review]
Very nice, thank you for the detailed documentation and tests. Could you maybe run `yarn lint` in folder `packages/adblocker-puppeteer` and maybe `yarn format-fix` at the *root* of the repository, I'd like the style of the code base to remain consistent if possible.

**Comment by remusao** [comment]
After merging this https://github.com/cliqz-oss/adblocker/pull/1903 we now have a few conflicts here, sorry about that. Also a note about tests, we have started using `express` in this other PR to run a local server during tests, would you mind updated the tests from this PR to use it as well?

**Comment by Tyler-Murphy** [comment]
I think this was made irrelevant by https://github.com/puppeteer/puppeteer/pull/7217, which was released in [v10.0.0](https://github.com/puppeteer/puppeteer/releases/tag/v10.0.0).

**Comment by remusao** [comment]
> I think this was made irrelevant by [puppeteer/puppeteer#7217](https://github.com/puppeteer/puppeteer/pull/7217), which was released in [v10.0.0](https://github.com/puppeteer/puppeteer/releases/tag/v10.0.0).

Even better! I will just release a new version of the adblocker with this new v10 tag in the list of Puppeteer versions then.

Tank you.

**Pull request closed without merging**
