### PR TITLE
Update uBlock Origin to use npm package

### PR DESCRIPTION
**Pull request by mjethani**
Using the new `StaticNetFilteringEngine` class from [@gorhill/ubo-core](https://www.npmjs.com/package/@gorhill/ubo-core).

### CODE REVIEW

**Comment by mjethani** [comment]
@gorhill please take a look first. It seems to be blocking more requests now! Try to clone https://github.com/mjethani/adblocker and switch to the update-ubo-core branch.

**Comment by gorhill** [comment]
Weird, I will investigate. What was the previous version?

On my side I used built-in benchmark to compare current master with 1.37.3b4 and I got same result.

**Comment by mjethani** [comment]
> What was the previous version?

```diff
@@ -1 +1 @@
-Subproject commit 543e1a3aea0c775ee34b7f168388a9ebaef1b4c5
+Subproject commit d9adf5a6fb688d470e67204501fdee176f9b4d4a
```

If it helps, I tried with `enableWASM()` and I also checked that the `type` value is being propagated to the engine. This must be something wrong with the way I'm using it here or otherwise with the changes that involve the moving around of the parser, compiler, etc.

**Comment by mjethani** [comment]
This works until https://github.com/gorhill/uBlock/commit/65f0909ba08c938473ab45f7b54aa31cc9d49a3a

**Comment by mjethani** [comment]
> This works until [gorhill/uBlock@65f0909](https://github.com/gorhill/uBlock/commit/65f0909ba08c938473ab45f7b54aa31cc9d49a3a)

By this I mean that it works in that commit too. It probably broke in the one that followed. Let me confirm this.

**Comment by mjethani** [comment]
> > This works until [gorhill/uBlock@65f0909](https://github.com/gorhill/uBlock/commit/65f0909ba08c938473ab45f7b54aa31cc9d49a3a)
> 
> By this I mean that it works in that commit too. It probably broke in the one that followed. Let me confirm this.

Confirmed. It broke in https://github.com/gorhill/uBlock/commit/7cd583a301a84d269587e1afcb883de78d359374. In that commit it blocks 85,131 requests. It should block 82,388 requests.

**Comment by gorhill** [comment]
When I compare on my side using built-in benchmark which uses all default filter lists, I get 94,560 for both before and after that commit. This suggests the issue is in a code path not used by the extension.

**Comment by mjethani** [comment]
> When I compare on my side using built-in benchmark which uses all default filter lists, I get 94,560 for both before and after that commit. This suggests the issue is in a code path not used by the extension.

It's almost certainly in [`platform/nodejs/index.js`](https://github.com/gorhill/uBlock/commit/7cd583a301a84d269587e1afcb883de78d359374#diff-e032111c993d2dc802ee0b46ea1493a83de32127e09a445361b85f1402ebcbf1).

**Comment by gorhill** [comment]
Looks like `loadJSON('build/publicsuffixlist.json')` is returning an empty string.

**Comment by mjethani** [comment]
> Looks like `loadJSON('build/publicsuffixlist.json')` is returning an empty string.

https://github.com/gorhill/uBlock/pull/3807

**Comment by mjethani** [comment]
@gorhill @remusao fixed now and ready for review.

**Comment by mjethani** [comment]
@gorhill if you publish a new version to npm, I'll update this patch to use the npm version directly just as we do with [adblock-rs](https://www.npmjs.com/package/adblock-rs) and [@adguard/tsurlfilter](https://www.npmjs.com/package/@adguard/tsurlfilter).

**Comment by gorhill** [comment]
> @gorhill if you publish a new version to npm, I'll update this patch to use the npm version

Done: <https://www.npmjs.com/package/@gorhill/ubo-core>

**Comment by mjethani** [comment]
> > @gorhill if you publish a new version to npm, I'll update this patch to use the npm version
> 
> Done: https://www.npmjs.com/package/@gorhill/ubo-core

@remusao I've updated the patch now to remove the git submodule and use the npm package directly.

**Review by remusao — APPROVED** [review]

**Pull request merged**
