### PR TITLE
Update puppeteer to v7.x

### LINKED ISSUE #1674: Support for puppeteer 7.x
I looks the package `adblocker-puppeteer` does not support the latest versions of puppeteer. 
Would it be possible to add support for the latest puppeteer versions ? 

Let me know if there is anything I can do to help! :)

### PR DESCRIPTION
**Pull request by remusao**
Update puppeteer to latest version. Fixes #1674

### CODE REVIEW

**Comment by TimotheeJeannin** [comment]
Hi @remusao, Thank you for this pull request! 

When I tested the current version of @cliqz/adblocker-puppeteer with puppeteer 7.x, it was failing to apply some rules I think. For example cookies where not blocked with 7.x.

The diff looks good to me, but I don't how I can install @cliqz/adblocker-puppeteer from a pull request, so I haven't tried to check if it fixes the issue. 

Thank you again for the amazing work!

**Comment by remusao** [comment]
Thanks @TimotheeJeannin, I did some local testing and it seems to work as intended. I'm gonna merge and release this so that we can test more extensively but I do not expect breakage.

**Comment by berstend** [comment]
FWIW removing `@types/puppeteer` broke `puppeteer-extra-plugin-adblocker` - I pinned the dependency to `@cliqz/adblocker-puppeteer@1.18.7` for the time being.

Puppeteer messed up typings real good by shipping with their broken internal ones, I'm tracking the situation here: https://github.com/berstend/puppeteer-extra/issues/428

**Comment by remusao** [comment]
Hey @berstend, thanks for letting me know. I only encountered one issue with the types (which has since been fixed) and did not think that it would cause an issue with `puppeteer-extra`. Sorry for that. Hopefully they fix it soon upstream!

**Pull request merged**
