### PR TITLE
Implement converter from filters to safari blocking rules

### PR DESCRIPTION
**Pull request by remusao**
This is a prototype to convert adblocker filters to Safari blocking rules. With the current version:

- 676085 filters were converted
- The resulting JSON file is 8.4MB (685k compressed with gzip)
- Unit tests will make sure that all filters are converted into valid Safari rules

Thanks to @timotei-cliqz for doing most of the work.

This is a good first version, but in the future it would be nice to extend the tests to also make sure that the transformation to safari rules preserves the semantic of each filter.

### CODE REVIEW

**Comment by timotei-cliqz** [comment]
@chrmod we don't know yet if 9mb is too much. I haven't seen anything in the docs about it. @remusao is right, there seems to be a limit. Will keep you (both) posted.

**Comment by timotei-cliqz** [comment]
@remusao here is what I found: 
1) Fields with empty values are not allowed
2) One action type is wrong. "ignore-previous-rule" should be "ignore-previous-rules" (s missing at the end).
3) The "trigger" field has to have a "url-filter" value. If the rule is supposed to apply to all urls, the "url-filter" field should have ".*" as a value.

Additionally, I have found some issues with the values of "url-filter":
1) "^*" - Example: (.*)?amazonaws.com/^*/abb-msg.js
2) "^" at the end - Example: &pltype=adhost^
3) "+" at the beginning - Example: +advertorial.
4) "|" at the end - Example: /addyn|
5) "|" inside - Example: /addyn|*|adtech 
6) "?*" anywhere - Example: - [ ] /eas?*^easformat=
7) "?" at the beginning - Example: ?action=ads&

Some comments: 

According to the doc: []( https://developer.apple.com/library/content/documentation/Extensions/Conceptual/ContentBlockingRules/CreatingRules/CreatingRules.html)

**Comment by remusao** [comment]
The pull request has been updated with changes from Tim. Whoever merges this should probably squash and create a nice commit message. The history is a bit messy.

**Comment by remusao** [comment]
Closing this for now. We might continue this work in the future if needed.

**Pull request closed without merging**
